version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ~/apps/postgres2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=kalinduauto
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: devx10@devx10.com
      PGADMIN_DEFAULT_PASSWORD: devx10
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - default
    depends_on:
      - postgres

volumes:
  pgadmin-data:
