version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=devx10@69
      - POSTGRES_USER=devx10
      - POSTGRES_DB=kalinduauto
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: devx10@devx10.com
      PGADMIN_DEFAULT_PASSWORD: devx10
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - default
    depends_on:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://kalinduauto.devx10.live:5432/kalinduauto
      KC_DB_USERNAME: devx10
      KC_DB_PASSWORD: devx10@69

      KC_HOSTNAME: kalinduauto.devx10.live
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - postgres
      - pgadmin
    ports:
      - 8080:8080


volumes:
  pgdata:
  pgadmin-data:
  
